apiVersion: spdx.softwarecomposition.kubescape.io/v1alpha1
kind: Framework
metadata:
  name: framework-1
controlsRef:
  - name: control-1
    controlID: C-001
    kind: Control
    apiVersion: v1alpha1
blob:
  description: This is framework-1